### ISSUE TITLE
Is there some limitations with Notion database and if so, what can be done

### ISSUE THREAD

**Issue by Yutcam** [dust-tt/dust#1204] opened 2023-08-31 10:09 UTC
we got several feedback from our users - [Pennylane](https://dust4ai.slack.com/archives/C05A4RWJQKC/p1691655093372539?thread_ts=1691597322.449189&cid=C05A4RWJQKC) and [Photoroom](https://dust4ai.slack.com/archives/C05LP5CMY10/p1691684457351119), who were not certain that Dust could access database. 

- it seems that even when you write the name of the page in full words to retrieve its content sometimes the semantic search makes it difficult to find the relevant data. 
- also, when the user know a database does exist, their first behaviour is to ask more "analytical" questions, like 'how many competitors do we have inside our bench", or list the name of the owner and their pets like Matthieu did. Those use cases are not well supported by semantic search. 

Changing the behaviour here seems quite difficult and still a minor use case, so the question is: is there quick fixes we can identify to better support the Pennylane use case for example. @fontanierh suggested better surfacing the title maybe (please add your thoughts on this Henry). And/or could we clarify what is possible and not possible with Notion database to manage our user expectations.

**Comment by Yutcam** [comment] 2023-08-31 10:16
Eng runner board

**Comment by spolu** [comment] 2023-09-01 07:20
Duplicate of #1202

**Closed by spolu** 2023-09-01 07:20 UTC
Labels: eng-runner
