### ISSUE TITLE
When no assistant is pingged, we suggest assistants to answer.

### ISSUE THREAD

**Issue by Duncid** [dust-tt/dust#1593] opened 2023-09-20 08:48 UTC
![Image](https://github.com/dust-tt/dust/assets/4435185/78a7aa53-6a15-4ae8-9b0f-dcc779217f31)

**Comment by spolu** [comment] 2023-09-20 09:36
Duplicate of #1565 :pray:

**Closed by spolu** 2023-09-20 09:36 UTC
