### ISSUE TITLE
Datasource Website - Internal Server Error

### ISSUE THREAD

**Issue by JulesBelveze** [dust-tt/dust#5906] opened 2024-06-27 09:05 UTC
I am getting 500s every now and then when trying to modify a website

**Comment by tdraier** [comment] 2024-06-27 09:21
It seems we are hitting a rate limit when accessing connectors 
http://connectors-service/connectors/4889/permissions?viewType=documents&filterPermission=read
-> "Too many requests"

**Comment by spolu** [comment] 2024-06-29 19:39
Working on it

Closing as duplicate of https://github.com/dust-tt/tasks/issues/805

**Closed** 2024-06-29 19:40 UTC
