### ISSUE TITLE
Improve managed data source without content nodes

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#7363] opened 2024-09-12 17:43 UTC
When a data source is freshly connected, if the admin does not select any node, it still shows up in the "Company Data" but display a wide empty gray rectangle. If not admin we should display a request CTA for admins see https://github.com/dust-tt/dust/issues/7358.

![Image](https://github.com/user-attachments/assets/d41697f0-ff67-4d13-939d-19e8480882f2)

**Comment by JulesBelveze** [comment] 2024-09-13 06:10
Duplicate of https://github.com/dust-tt/tasks/issues/1315

**Closed** 2024-09-13 07:33 UTC
