### ISSUE TITLE
[Vaults UI] Plumbing for view to see a document

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6900] opened 2024-08-26 08:03 UTC
Use the new `DataSourceViewDocumentModal` in the overflow menu of the list item.

**Comment by PopDaph** [comment] 2024-09-05 06:49
@flvndvd are you already working on this? 
I realize the one of the card I created is partly a duplicate of this one: https://github.com/dust-tt/tasks/issues/1238.

**Comment by flvndvd** [comment] 2024-09-05 07:35
Yep I shipped the component and just miss a few places to use it.

**Comment by PopDaph** [comment] 2024-09-05 09:35
Nice! Then I unassigned myself and assigned you to the other task. 
Since this one does not have a real description I'm not sure the overlap was 100% between both task so I'll let you check and add the missing things if any 🙏🏻

**Closed** 2024-09-06 16:27 UTC
