### ISSUE TITLE
If say yes to leave page with unsaved changes, does not leave page

### ISSUE THREAD

**Issue by aamorel** [dust-tt/dust#159] opened 2023-03-08 16:08 UTC
Inside the Dust webapp, when you create a Dataset, if you want to leave the page with unsaved changes (for example by clicking on Specification), it asks for confirmation which is normal.

But if you say OK, it still keeps you on the Dataset page. 

Small bug but could be nice to fix. 

Is there a contributing policy ?

**Comment by spolu** [comment] 2023-03-08 16:13
Thanks for reporting.

You are welcomed to contribute by just submitting a pull-request of course. Will separately look into it :+1:

**Comment by spolu** [comment] 2023-03-08 16:14
Just tested it and clicking OK seems to work on my end... will investigate more.

**Comment by spolu** [comment] 2023-03-22 17:50
Was not able to reproduce. Closing for now. Feel free to reopen :+1:

**Closed by spolu** 2023-03-22 17:50 UTC
