### ISSUE TITLE
Tab `Use` is not displaying any output

### ISSUE THREAD

**Issue by ninehills** [dust-tt/dust#208] opened 2023-04-02 00:35 UTC
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/270298/229324235-ba18141a-c00a-408b-adf1-b17eb0dc451e.png">

**Comment by spolu** [comment] 2023-04-02 14:00
Hi! It looks like a regression indeed. cc @fontanierh ? I believe it's likely one of your PRs?

**Comment by spolu** [comment] 2023-04-02 14:09
The app works it's just that the UI does not update until it completes.

The PR above fixes that.

**Comment by spolu** [comment] 2023-04-02 14:14
That does not seem like the only issue. Will continue investigating :+1:

**Comment by spolu** [comment] 2023-04-02 14:19
@fontanierh haven't found the issue yet. Will investigate more later today.

The weird thing is that locally it works well (it was not streaming but did work. The PR fixed everything and locally it does stream the updates to the UI and work as expected)

In production there is no UI udpate and things don't work.

:thinking:

**Comment by spolu** [comment] 2023-04-02 16:35
We're getting the following error from production in the `streamChunks` function:
```
ERROR streaming from Dust API TypeError: stream.getReader is not a function
    at streamChunks (/home/spolu/code/dust/front/.next/server/pages/api/apps/[user]/[sId]/runs.js:240:27)
    at streamChunks.next (<anonymous>)
    at handler (/home/spolu/code/dust/front/.next/server/pages/api/apps/[user]/[sId]/runs.js:150:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.apiResolver (/home/spolu/code/dust/front/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/home/spolu/code/dust/front/node_modules/next/dist/server/next-server.js:514:9)
    at async Object.fn (/home/spolu/code/dust/front/node_modules/next/dist/server/next-server.js:828:35)
    at async Router.execute (/home/spolu/code/dust/front/node_modules/next/dist/server/router.js:243:32)
    at async NextNodeServer.runImpl (/home/spolu/code/dust/front/node_modules/next/dist/server/base-server.js:432:29)
```

**Comment by spolu** [comment] 2023-04-02 16:36
Likely a node version issue will bump node there

**Comment by spolu** [comment] 2023-04-02 16:36
(to v18.15.0)

**Comment by spolu** [comment] 2023-04-02 16:41
Done. now fixed.

**Comment by spolu** [comment] 2023-04-02 16:42
@ninehills sorry for that. Thanks for reporting :+1:

**Closed by spolu** 2023-04-02 16:41 UTC
