### ISSUE TITLE
Offer possibility to new users to join existing workspace

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#3154] opened 2024-01-11 15:09 UTC
This GitHub issue addresses the current user experience on Dust, where new users who sign up without an invitation link are automatically assigned to a new, isolated workspace. This situation prevents them from experiencing the collaborative benefits of Dust. 

To enhance security and ensure the integrity of this process, the approach will be limited exclusively to users who sign up through the Google Auth flow and are attempting to join a workspace where their email domain has been previously verified and whitelisted. Moreover, we will implement a domain validation procedure for companies when they opt to whitelist their domain. This additional security measure ensures that only authorized users are granted access to their workspace. 

The proposed solution involves presenting a new screen to users who sign up via Google Auth, allowing them to join an existing workspace if their email domain matches a domain that has been pre-approved and whitelisted.

Implementing this feature would greatly diminish the initial friction users face by immediately integrating them into a community on Dust, providing them with immediate access to the platform's full potential.

**Comment by flvndvd** [comment] 2024-01-11 15:09
CC @Duncid can you help on this part?
> The proposed solution involves presenting a new screen to users who sign up via Google Auth, allowing them to join an existing workspace if their email domain matches a domain that has been pre-approved and whitelisted.

**Comment by Duncid** [comment] 2024-01-11 15:37
# My understanding
## Current experience

- As a user with a company email (ed@mycompany.com), I'd like to join the dust workspace of my company.

- Case A: the domain **has been white listed by the Admin.**
  - I go to dust.tt, do google signup, and **I land on the company workspace as intended** (So, success)

- Case B: the domain **has not been white listed by the Admin.**
  - Case B1: **I have not been invited, I'm using the link**
    - I follow the link, I join the workspace (So, success)
  - Case B2: **I have not been invited**,
    - I go to dust.tt, do google signup, and I'm lead to create a new workspace (Fail).
  - Case B3: **I have been invited** but I am not using the invitation link
    - I go to dust.tt, do google signup, and I'm lead to create a new workspace (Fail).

**Is that correct?**

Which case is of interest to you now?

**Comment by flvndvd** [comment] 2024-01-11 15:44
> Case A: the domain has been white listed by the Admin.
> - I go to dust.tt, do google signup, and I land on the company workspace as intended (Success)

This is not accurate. Today if you browse to dust.tt directly, you'll never land in any workspace, even though your domain has been whitelisted.

The only way to join a workspace is to follow one of an invitation link like pointed out in Case B.

This issue focuses on case A.

**Comment by Duncid** [comment] 2024-01-11 16:21
# Revisited understanding
## Current experience

- As a user with a company email (ed@mycompany.com), I'd like to join the dust workspace of my company.

- Case A: the domain **has been whitelisted by the Admin.**
  - Case A1: I have the invitation link
    - I use the link, do google signup, and **I land on the company workspace as intended** (**Success**)
  - Case A2: I don't have or don't use the invitation link
    - I go to dust.tt, do google signup, and **I land on the company workspace as intended** (**Fail**)

- Case B: the domain **has not been white listed by the Admin.**
  - Case B1: **I have not been invited, I'm using the link**
    - I follow the link, I join the workspace (**Success**)
  - Case B2: **I have not been invited**,
    - I go to dust.tt, do google signup, and I'm lead to create a new workspace (**Fail**).
  - Case B3: **I have been invited** but I am **not using the invitation link**
    - I go to dust.tt, do google signup, and I'm lead to create a new workspace (**Fail**).

**Is that correct?**

## The proposal

> The proposed solution involves presenting a new screen to users who sign up via Google Auth, allowing them to join an existing workspace if their email domain matches a domain that has been pre-approved and whitelisted.

So I understand the proposal is that in case A2, we propose to the user who authentified with the email of a whitelisted domain name to join the workspace associated to the domain.

**Correct?**

**Comment by flvndvd** [comment] 2024-01-11 16:58
> So I understand the proposal is that in case A2, we propose to the user who authentified with the email of a whitelisted domain name to join the workspace associated to the domain.
>
> Correct?

This is correct.

**Comment by Duncid** [comment] 2024-01-11 17:23
Ok, so here are my thoughts:
I'm not sure why we would want to keep a link in that case.

There are two jobs we may want to do with this link thing:
- 1 - Avoid having to invite each member one by one by hand
- 2 - Avoid all people in the company to be able to join the workspace (Only those with the link)


Job 1 is pretty well done with just domain whitelist (signup with a domain whitelisted OAuth and your's in the workspace).
Job 2 is no very well done by the link as the link is the same for everyone it can very easily "leak" in the company.

IMO we can forget about the link.

**Comment by philipperolet** [comment] 2024-05-21 08:58
Hey 👋

Most of important cases have been adressed, since a user signing in with a company email is now directed to the company workspace if the domain has been whitelisted or they received a link. Checked with @flvndvd we're good on this

Closing; if there are remaining cases somebody thinks we should address in the coming week or two, feel free to submit an updated card.

**Closed by philipperolet** 2024-05-21 08:58 UTC
